# Generated by Django 2.2.2 on 2020-12-12 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='', max_length=100, null=True)),
                ('role_code', models.CharField(default='', max_length=100, null=True)),
                ('role_status', models.CharField(default='', max_length=50, null=True)),
                ('user_created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.CharField(default='', max_length=250, null=True)),
                ('username', models.CharField(default='', max_length=1000, null=True)),
                ('password', models.CharField(default='', max_length=250, null=True)),
                ('status', models.CharField(default='active', max_length=50, null=True)),
                ('user_created_time', models.DateTimeField(auto_now_add=True)),
                ('count_logins', models.IntegerField(default=0)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.Role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
