# Generated by Django 2.2.2 on 2020-12-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departments', models.CharField(default='', max_length=250, null=True)),
                ('categories', models.CharField(default='', max_length=250, null=True)),
                ('priorities', models.CharField(default='', max_length=250, null=True)),
            ],
            options={
                'db_table': 'ticket_details',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='count_logins',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.AddField(
            model_name='user',
            name='useremail',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
